{{ range $idx, $environment := .Values.jxRequirements.environments }}
{{- if $environment.remoteCluster }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $environment.key }}-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ $environment.key }}
  server: {{ $environment.url }}
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
      {{- if eq $.Values.jxRequirements.cluster.provider "gke" }}
        "args": ["gcp"],
      {{- else if eq $.Values.jxRequirements.cluster.provider "eks" }}
        "args": ["aws"],
      {{- else if eq $.Values.jxRequirements.cluster.provider "aks" }}
        "args": ["azure"],
      {{- else }}
      {{- end }}
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
{{ end }}
{{ end }}
