# additional applicationset configuration
extraConfig: {}
# extraConfig:
#   foo:
#     bar: baz

# [argo-cd application sync policy](https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/)
syncPolicy: # +doc-gen:break
  automated:
    prune: true
    selfHeal: true
  syncOptions:
  - CreateNamespace=true

projects:
  # required to allow permissions to create clusterroles and clusterrolebindings
  clusterResourceWhitelist: # +doc-gen:break
  - group: '*'
    kind: '*'

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    # shared ingress annotations on all services
    annotations: {}
    #  kubernetes.io/ingress.class: nginx

    apiVersion: "networking.k8s.io/v1"

    # the domain for hosts
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""
